### ANALYSIS  on Washing Machine from Flipkart

In [30]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [31]:
df=pd.read_csv(r"C:\Users\DELL\DATA SCIENCE\MY OWN GROUP\NEW WASHING.csv")

In [32]:
df

     Unnamed: 0     Brands   Prices  Capacity   RPM  LOADS  Rating  Warranty
0             0    SAMSUNG  ₹14,490       6.5   680  Fully       3         2
1             1    SAMSUNG  ₹18,490       7.0   750  Fully       5         3
2             2  Whirlpool   ₹9,990       7.0    12   Semi       5         2
3             3    SAMSUNG  ₹36,990       8.0  1450   Semi       5         3
4             4         LG  ₹11,190       7.0  1400  Fully       5         2
..          ...        ...      ...       ...   ...    ...     ...       ...
437         437         LG  ₹40,968       6.5    10   Semi       5         3
438         438  Whirlpool  ₹13,990       9.5   700   Semi       5         2
439         439    SAMSUNG  ₹31,990       7.0    10   Semi       5         2
440         440         LG  ₹36,199       6.0  1500   Semi       5         2
441         441      BOSCH  ₹41,900       7.0  1000   Semi       5         2

[442 rows x 8 columns]

 ### The Pandas drop () function in Python is used to drop specified labels from rows and columns. Drop is a major function used to clean the dataset.

In [33]:
df1 = df.drop('Unnamed: 0',axis=1)
df1

        Brands   Prices  Capacity   RPM  LOADS  Rating  Warranty
0      SAMSUNG  ₹14,490       6.5   680  Fully       3         2
1      SAMSUNG  ₹18,490       7.0   750  Fully       5         3
2    Whirlpool   ₹9,990       7.0    12   Semi       5         2
3      SAMSUNG  ₹36,990       8.0  1450   Semi       5         3
4           LG  ₹11,190       7.0  1400  Fully       5         2
..         ...      ...       ...   ...    ...     ...       ...
437         LG  ₹40,968       6.5    10   Semi       5         3
438  Whirlpool  ₹13,990       9.5   700   Semi       5         2
439    SAMSUNG  ₹31,990       7.0    10   Semi       5         2
440         LG  ₹36,199       6.0  1500   Semi       5         2
441      BOSCH  ₹41,900       7.0  1000   Semi       5         2

[442 rows x 7 columns]

### shape()  is  used  to  get   no of   rows and  columns  in data

In [34]:
df.shape

(442, 8)

### The info () function is used to print a concise summary of a DataFrame

#### . concise   means  lot of information

In [35]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Brands    442 non-null    object
 1   Prices    442 non-null    object
 2   Capacity  442 non-null    float64
 3   RPM       442 non-null    int64
 4   LOADS     442 non-null    object
 5   Rating    442 non-null    int64
 6   Warranty  442 non-null    int64
dtypes: float64(1), int64(3), object(3)
memory usage: 24.3+ KB

In [36]:
len(df1)

442

###   here  created  empty list to  remove ₹ symbol  in prices  i have used  repace()

In [37]:
a = []
for i in df1['Prices']:
    a.append(i.replace("₹","").replace(",",""))
    
df1['Prices']  = a

In [38]:
df1

        Brands Prices  Capacity   RPM  LOADS  Rating  Warranty
0      SAMSUNG  14490       6.5   680  Fully       3         2
1      SAMSUNG  18490       7.0   750  Fully       5         3
2    Whirlpool   9990       7.0    12   Semi       5         2
3      SAMSUNG  36990       8.0  1450   Semi       5         3
4           LG  11190       7.0  1400  Fully       5         2
..         ...    ...       ...   ...    ...     ...       ...
437         LG  40968       6.5    10   Semi       5         3
438  Whirlpool  13990       9.5   700   Semi       5         2
439    SAMSUNG  31990       7.0    10   Semi       5         2
440         LG  36199       6.0  1500   Semi       5         2
441      BOSCH  41900       7.0  1000   Semi       5         2

[442 rows x 7 columns]

In [39]:
df1["Prices"]=pd.to_numeric(df1["Prices"])

In [40]:
df1["Prices"]

0      14490
1      18490
2       9990
3      36990
4      11190
       ...
437    40968
438    13990
439    31990
440    36199
441    41900
Name: Prices, Length: 442, dtype: int64

In [48]:
df1.head(10)

      Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
0    SAMSUNG   14490       6.5   680  Fully       3         2
1    SAMSUNG   18490       7.0   750  Fully       5         3
2  Whirlpool    9990       7.0    12   Semi       5         2
3    SAMSUNG   36990       8.0  1450   Semi       5         3
4         LG   11190       7.0  1400  Fully       5         2
5         LG   17990       7.0    10   Semi       5         2
6         LG   14990       8.5  1350   Semi       5         2
7    SAMSUNG   31990       8.0   700  Fully       5         3
8       MarQ    6990       6.0    10   Semi       5         2
9     realme   14990       8.0  1300  Fully       5         2

In [42]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Brands    442 non-null    object
 1   Prices    442 non-null    int64
 2   Capacity  442 non-null    float64
 3   RPM       442 non-null    int64
 4   LOADS     442 non-null    object
 5   Rating    442 non-null    int64
 6   Warranty  442 non-null    int64
dtypes: float64(1), int64(4), object(2)
memory usage: 24.3+ KB

### describe () in Python The describe () method is used for calculating some statistical data like percentile, mean and std of the numerical values of the Series or DataFrame

In [14]:
df1.describe()

              Prices    Capacity          RPM      Rating    Warranty
count     442.000000  442.000000   442.000000  442.000000  442.000000
mean    21573.457014    7.321719   648.871041    4.979638    2.343891
std     11936.502529    0.886957   602.441182    0.195277    0.638395
min      4990.000000    3.000000    10.000000    3.000000    1.000000
25%     12690.000000    6.500000    10.000000    5.000000    2.000000
50%     17990.000000    7.200000   700.000000    5.000000    2.000000
75%     29990.000000    8.000000  1300.000000    5.000000    3.000000
max    109090.000000    9.500000  2000.000000    5.000000    4.000000

###  isnull  is  used  to get  all  the null  values

In [15]:
df1.isnull().sum()

Brands      0
Prices      0
Capacity    0
RPM         0
LOADS       0
Rating      0
Warranty    0
dtype: int64

In [16]:
df1.describe()

              Prices    Capacity          RPM      Rating    Warranty
count     442.000000  442.000000   442.000000  442.000000  442.000000
mean    21573.457014    7.321719   648.871041    4.979638    2.343891
std     11936.502529    0.886957   602.441182    0.195277    0.638395
min      4990.000000    3.000000    10.000000    3.000000    1.000000
25%     12690.000000    6.500000    10.000000    5.000000    2.000000
50%     17990.000000    7.200000   700.000000    5.000000    2.000000
75%     29990.000000    8.000000  1300.000000    5.000000    3.000000
max    109090.000000    9.500000  2000.000000    5.000000    4.000000

In [17]:
df1["LOADS"]

0      Fully
1      Fully
2       Semi
3       Semi
4      Fully
       ...
437     Semi
438     Semi
439     Semi
440     Semi
441     Semi
Name: LOADS, Length: 442, dtype: object

###   to get  total brands  in   dat frame   we use   unique

In [18]:
df1['Brands'].unique()

array(['SAMSUNG', 'Whirlpool', 'LG', 'MarQ', 'realme', 'IFB', 'Haier',
       'Thomson', 'Candes', 'ONIDA', 'BOSCH', 'Godrej', 'Croma',
       'MOTOROLA', 'Sansui', 'Panasonic', 'Midea', 'Motorola', 'White',
       'Singer', 'Lifelong', 'TCL', 'Lloyd', 'Galanz', 'DMR', 'Voltas',
       'TOSHIBA', 'CANDY', 'Samsung', 'Hafele', 'RGL'], dtype=object)

In [19]:
df1['Brands'].value_counts()

SAMSUNG      88
Whirlpool    74
LG           62
IFB          38
Candes       29
MarQ         20
BOSCH        19
Godrej       13
Haier        10
ONIDA        10
MOTOROLA      9
White         7
Panasonic     7
Croma         7
realme        6
Galanz        6
Lloyd         6
Thomson       6
Sansui        4
Motorola      3
TCL           3
DMR           3
Voltas        3
Midea         2
Singer        1
Lifelong      1
TOSHIBA       1
CANDY         1
Samsung       1
Hafele        1
RGL           1
Name: Brands, dtype: int64

In [20]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Brands    442 non-null    object
 1   Prices    442 non-null    int64
 2   Capacity  442 non-null    float64
 3   RPM       442 non-null    int64
 4   LOADS     442 non-null    object
 5   Rating    442 non-null    int64
 6   Warranty  442 non-null    int64
dtypes: float64(1), int64(4), object(2)
memory usage: 24.3+ KB

In [21]:
df1['Prices'] = df1['Prices'].astype('int')

In [22]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Brands    442 non-null    object
 1   Prices    442 non-null    int32
 2   Capacity  442 non-null    float64
 3   RPM       442 non-null    int64
 4   LOADS     442 non-null    object
 5   Rating    442 non-null    int64
 6   Warranty  442 non-null    int64
dtypes: float64(1), int32(1), int64(3), object(2)
memory usage: 22.6+ KB

In [23]:
df1

        Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
0      SAMSUNG   14490       6.5   680  Fully       3         2
1      SAMSUNG   18490       7.0   750  Fully       5         3
2    Whirlpool    9990       7.0    12   Semi       5         2
3      SAMSUNG   36990       8.0  1450   Semi       5         3
4           LG   11190       7.0  1400  Fully       5         2
..         ...     ...       ...   ...    ...     ...       ...
437         LG   40968       6.5    10   Semi       5         3
438  Whirlpool   13990       9.5   700   Semi       5         2
439    SAMSUNG   31990       7.0    10   Semi       5         2
440         LG   36199       6.0  1500   Semi       5         2
441      BOSCH   41900       7.0  1000   Semi       5         2

[442 rows x 7 columns]

In [24]:
df7=df1.groupby(['Brands', 'Prices'])
df5= pd.DataFrame(df7)
df5

                   0                                                  1
0      (BOSCH, 9699)      Brands  Prices  Capacity  RPM  LOADS  Rati...
1     (BOSCH, 10290)     Brands  Prices  Capacity  RPM LOADS  Rating...
2     (BOSCH, 12990)      Brands  Prices  Capacity  RPM  LOADS  Rati...
3     (BOSCH, 14490)      Brands  Prices  Capacity   RPM LOADS  Rati...
4     (BOSCH, 17690)      Brands  Prices  Capacity  RPM LOADS  Ratin...
..               ...                                                ...
365  (realme, 13990)      Brands  Prices  Capacity  RPM LOADS  Ratin...
366  (realme, 14990)     Brands  Prices  Capacity   RPM  LOADS  Rati...
367  (realme, 17690)      Brands  Prices  Capacity  RPM  LOADS  Rati...
368  (realme, 30490)      Brands  Prices  Capacity  RPM  LOADS  Rati...
369  (realme, 34990)       Brands  Prices  Capacity  RPM  LOADS  Rat...

[370 rows x 2 columns]

In [25]:
df1.groupby(['Brands']).max()

           Prices  Capacity   RPM  LOADS  Rating  Warranty
Brands
BOSCH       43990       9.0  1500   Semi       5         4
CANDY       36690       6.0    10   Semi       5         2
Candes      56489       9.0  1500   Semi       5         4
Croma       40199       9.5  1440   Semi       5         4
DMR         13490       8.0  1200   Semi       5         4
Galanz      45490       8.0  1400   Semi       5         3
Godrej     109090       8.0  1400   Semi       5         4
Hafele      17690       6.0    10  Fully       5         2
Haier       30890       8.5  1400   Semi       5         4
IFB         40199       9.0  1500   Semi       5         4
LG          69990       9.0  1500   Semi       5         4
Lifelong    31990       6.0  1300  Fully       5         2
Lloyd       40990       8.5   800   Semi       5         4
MOTOROLA    40207       9.0  1400   Semi       5         4
MarQ        74990       8.5  1400   Semi       5         4
Midea       28999       8.0  1300   Semi       5         4
Motorola    34290       7.5    10   Semi       5         2
ONIDA       36990       9.5  1450   Semi       5         4
Panasonic   37330       8.5   800   Semi       5         3
RGL         16299       7.5    10   Semi       5         2
SAMSUNG     45990       9.0  2000   Semi       5         4
Samsung      9990       8.0    10  Fully       5         4
Sansui      17199       9.0  1500   Semi       5         3
Singer      15390       7.0    10   Semi       5         3
TCL         49959       9.0  1500   Semi       5         3
TOSHIBA     36990       7.2    15   Semi       5         3
Thomson     36990       9.0  1300   Semi       5         2
Voltas      13900       7.5  1400   Semi       5         2
Whirlpool   43699       9.5  1500   Semi       5         4
White       55900       8.0  1400   Semi       5         4
realme      34990       8.5  1300   Semi       5         3

In [26]:
grp = df1.groupby(['Brands', 'Capacity'])
for name, group in grp:
    print(name)
    print(group)
    print()

('BOSCH', 6.0)
    Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
28   BOSCH   24490       6.0   740   Semi       5         2
60   BOSCH   37990       6.0  1000  Fully       5         2
262  BOSCH   19590       6.0  1500   Semi       5         2

('BOSCH', 6.5)
    Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
140  BOSCH   39990       6.5  740   Semi       5         2
332  BOSCH   24990       6.5   10  Fully       5         2
369  BOSCH   29400       6.5   10  Fully       5         2

('BOSCH', 7.0)
    Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
38   BOSCH   28990       7.0    10   Semi       5         2
49   BOSCH   10290       7.0   800   Semi       5         3
89   BOSCH   32990       7.0  1450  Fully       5         2
405  BOSCH   21990       7.0    14   Semi       5         2
441  BOSCH   41900       7.0  1000   Semi       5         2

('BOSCH', 7.2)
    Brands  Prices  Capacity   RPM LOADS  Rating  Warranty
396  BOSCH   14490       7.2  1000  Semi       5         3

('BOSCH', 7.5)
    Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
342  BOSCH   17690       7.5   10  Semi       5         4

('BOSCH', 8.0)
    Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
86   BOSCH   31990       8.0    10  Fully       5         4
192  BOSCH   29900       8.0  1400  Fully       5         2
228  BOSCH   26690       8.0  1400  Fully       5         2

('BOSCH', 8.5)
    Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
233  BOSCH    9699       8.5   12  Fully       5         2
320  BOSCH   43990       8.5   10   Semi       5         2

('BOSCH', 9.0)
    Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
244  BOSCH   12990       9.0   10  Fully       5         2

('CANDY', 6.0)
    Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
352  CANDY   36690       6.0   10  Semi       5         2

('Candes', 6.0)
     Brands  Prices  Capacity   RPM LOADS  Rating  Warranty
155  Candes   27990       6.0  1450  Semi       5         2
333  Candes   33600       6.0  1400  Semi       5         3

('Candes', 6.5)
     Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
235  Candes   36990       6.5    10  Fully       5         2
255  Candes   19490       6.5  1400   Semi       5         3
335  Candes   35820       6.5  1400  Fully       5         2
351  Candes   34990       6.5    12  Fully       5         2
391  Candes   35290       6.5    10  Fully       5         2
419  Candes   38200       6.5    10   Semi       4         2

('Candes', 7.0)
     Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
175  Candes   20990       7.0  1400   Semi       5         2
211  Candes   25690       7.0    10  Fully       5         2
231  Candes   33990       7.0  1450  Fully       5         2
259  Candes   23499       7.0    10  Fully       5         2
395  Candes   56489       7.0  1500   Semi       5         2

('Candes', 7.2)
    Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
59  Candes   24990       7.2   12  Fully       5         2

('Candes', 7.5)
     Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
179  Candes   12290       7.5   740  Fully       5         2
411  Candes   20990       7.5  1200   Semi       5         2

('Candes', 8.0)
     Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
35   Candes    9699       8.0    10  Fully       5         4
63   Candes   12990       8.0  1000  Fully       5         2
79   Candes   14940       8.0    10   Semi       5         3
111  Candes   13990       8.0    10  Fully       5         2
199  Candes   10490       8.0  1450   Semi       5         2
319  Candes   13990       8.0  1200   Semi       5         3
375  Candes   17590       8.0    12   Semi       5         2

('Candes', 8.5)
     Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
307  Candes   10990       8.5    10  Fully       5         2
407  Candes   13640       8.5  1300  Fully       5         2

('Candes', 9.0)
     Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
23   Candes   10799       9.0    10   Semi       5         2
43   Candes   22990       9.0    10   Semi       5         4
271  Candes   31990       9.0  1400   Semi       5         2
295  Candes   31990       9.0    16  Fully       5         2

('Croma', 6.0)
    Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
252  Croma    8244       6.0   10  Fully       5         3

('Croma', 6.5)
    Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
46   Croma   40199       6.5   780   Semi       5         4
122  Croma   11240       6.5    22   Semi       5         1
401  Croma   30790       6.5  1440  Fully       5         2

('Croma', 7.5)
    Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
201  Croma   31990       7.5   15  Semi       5         3

('Croma', 9.0)
    Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
297  Croma   36090       9.0  700  Semi       5         3

('Croma', 9.5)
    Brands  Prices  Capacity   RPM LOADS  Rating  Warranty
229  Croma    8244       9.5  1000  Semi       5         3

('DMR', 7.0)
    Brands  Prices  Capacity   RPM LOADS  Rating  Warranty
250    DMR   13490       7.0  1200  Semi       5         2

('DMR', 7.5)
    Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
386    DMR    8244       7.5   10  Semi       5         4

('DMR', 8.0)
    Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
358    DMR   11240       8.0  740  Semi       5         2

('Galanz', 6.0)
     Brands  Prices  Capacity   RPM LOADS  Rating  Warranty
329  Galanz   45490       6.0  1400  Semi       5         2

('Galanz', 6.5)
     Brands  Prices  Capacity   RPM LOADS  Rating  Warranty
198  Galanz   31590       6.5  1300  Semi       5         2

('Galanz', 7.0)
     Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
310  Galanz   36990       7.0  800  Fully       5         3
420  Galanz   17690       7.0   10  Fully       5         2

('Galanz', 8.0)
     Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
197  Galanz    8244       8.0   15  Semi       5         2
308  Galanz   13490       8.0  740  Semi       5         2

('Godrej', 6.0)
     Brands  Prices  Capacity   RPM LOADS  Rating  Warranty
221  Godrej   31990       6.0  1300  Semi       5         3
356  Godrej    8499       6.0    10  Semi       5         3

('Godrej', 6.2)
     Brands  Prices  Capacity   RPM LOADS  Rating  Warranty
30   Godrej   12690       6.2  1000  Semi       5         3
393  Godrej   35990       6.2  1000  Semi       5         2

('Godrej', 6.5)
     Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
150  Godrej   14990       6.5  750   Semi       5         4
225  Godrej   17690       6.5   10   Semi       5         3
373  Godrej  109090       6.5   10  Fully       5         3

('Godrej', 7.0)
     Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
65   Godrej   17790       7.0  1300  Fully       5         2
336  Godrej   23990       7.0    15  Fully       5         2

('Godrej', 7.5)
     Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
382  Godrej   36990       7.5   10  Semi       5         2

('Godrej', 8.0)
     Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
234  Godrej   15290       8.0  1400   Semi       5         2
236  Godrej   15700       8.0    10  Fully       5         2
414  Godrej   35990       8.0    10   Semi       5         2

('Hafele', 6.0)
     Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
398  Hafele   17690       6.0   10  Fully       5         2

('Haier', 6.5)
   Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
16  Haier   13990       6.5  740   Semi       5         2
58  Haier    8244       6.5  740  Fully       5         2

('Haier', 7.0)
    Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
173  Haier    8244       7.0  1400   Semi       5         2
425  Haier   30890       7.0  1400  Fully       5         2

('Haier', 7.5)
    Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
129  Haier   10790       7.5    15  Fully       5         2
242  Haier   22999       7.5  1000   Semi       5         2

('Haier', 8.0)
    Brands  Prices  Capacity   RPM LOADS  Rating  Warranty
206  Haier   18490       8.0  1400  Semi       5         2
392  Haier   17990       8.0  1300  Semi       5         3

('Haier', 8.5)
    Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
113  Haier   14290       8.5   11  Fully       5         2
185  Haier   17690       8.5   10  Fully       5         4

('IFB', 6.0)
    Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
12     IFB   20990       6.0  1350  Fully       5         4
44     IFB   10790       6.0  1400   Semi       5         2
124    IFB    7490       6.0   720   Semi       5         2
376    IFB   11799       6.0    10   Semi       5         2

('IFB', 6.5)
    Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
18     IFB   24990       6.5   800   Semi       5         4
40     IFB   29990       6.5  1350  Fully       5         3
56     IFB    7490       6.5    10   Semi       5         2
161    IFB   31990       6.5    12  Fully       5         2
186    IFB   32990       6.5  1300  Fully       5         3
260    IFB   14890       6.5  1000  Fully       5         2
266    IFB   17590       6.5  1400   Semi       5         2

('IFB', 7.0)
    Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
36     IFB   28990       7.0  1400   Semi       5         2
48     IFB   30990       7.0    10  Fully       5         2
84     IFB   16990       7.0    10   Semi       5         2
169    IFB   36990       7.0  1300  Fully       5         3
406    IFB    7274       7.0    10  Fully       5         2

('IFB', 7.2)
    Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
354    IFB   40199       7.2  740  Fully       5         2

('IFB', 7.5)
    Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
94     IFB   17690       7.5  1400  Fully       5         3
205    IFB   17690       7.5  1300  Fully       5         3
302    IFB    9699       7.5  1350  Fully       5         2
330    IFB    9699       7.5    10   Semi       5         2
345    IFB   26089       7.5  1300   Semi       5         2
434    IFB   23990       7.5    10   Semi       5         2

('IFB', 8.0)
    Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
61     IFB   31990       8.0    10   Semi       5         2
138    IFB   30990       8.0  1200  Fully       5         2
149    IFB   36990       8.0    10   Semi       5         2
178    IFB   10490       8.0    10  Fully       5         2
200    IFB   19590       8.0  1400  Fully       5         2
202    IFB    7990       8.0  1000  Fully       5         2
230    IFB   27990       8.0    10   Semi       5         2
232    IFB    9790       8.0  1200   Semi       5         2
237    IFB   40199       8.0  1400   Semi       5         2
422    IFB   22870       8.0  1450  Fully       5         2
432    IFB   36990       8.0   680  Fully       5         2

('IFB', 8.5)
    Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
158    IFB   23990       8.5  1400   Semi       5         3
301    IFB   14690       8.5  1500  Fully       5         2

('IFB', 9.0)
    Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
72     IFB    6490       9.0  700  Semi       5         2
400    IFB   29690       9.0   12  Semi       5         2

('LG', 3.0)
    Brands  Prices  Capacity   RPM LOADS  Rating  Warranty
340     LG   23490       3.0  1300  Semi       5         3

('LG', 5.2)
    Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
428     LG   11240       5.2  240  Fully       5         2

('LG', 6.0)
    Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
152     LG   26990       6.0    12  Fully       5         2
418     LG   14799       6.0   680   Semi       5         2
440     LG   36199       6.0  1500   Semi       5         2

('LG', 6.5)
    Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
14      LG   16690       6.5    10   Semi       5         2
21      LG   25990       6.5    12  Fully       5         2
100     LG   17990       6.5    10  Fully       5         2
134     LG   22490       6.5   680  Fully       5         2
166     LG    9990       6.5  1000  Fully       5         2
188     LG   17990       6.5   700  Fully       5         4
292     LG   32390       6.5  1500   Semi       5         3
357     LG   13290       6.5  1200  Fully       5         2
364     LG   27400       6.5    15  Fully       5         4
408     LG   16990       6.5  1400  Fully       5         4
430     LG   69990       6.5   740   Semi       5         2
433     LG   28990       6.5    10  Fully       5         2
437     LG   40968       6.5    10   Semi       5         3

('LG', 7.0)
    Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
4       LG   11190       7.0  1400  Fully       5         2
5       LG   17990       7.0    10   Semi       5         2
109     LG    7890       7.0  1200   Semi       5         2
121     LG    8490       7.0  1400   Semi       5         2
128     LG   14990       7.0  1400  Fully       5         4
142     LG   26590       7.0  1400   Semi       5         2
213     LG   14890       7.0    10   Semi       5         2
240     LG   13290       7.0   740   Semi       5         2
316     LG   15790       7.0    12  Fully       5         2
322     LG   17690       7.0  1450  Fully       5         4
346     LG    8244       7.0  1400  Fully       5         2
390     LG    7274       7.0   680  Fully       5         2
413     LG    8244       7.0  1300  Fully       5         3

('LG', 7.2)
    Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
193     LG   36990       7.2   10   Semi       5         3
222     LG   22229       7.2  700  Fully       5         2
282     LG    9990       7.2   10   Semi       5         2

('LG', 7.5)
    Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
37      LG   12690       7.5  1000   Semi       5         2
108     LG   21490       7.5    10  Fully       5         2
182     LG   19790       7.5  1400   Semi       5         3
281     LG   23500       7.5  1000  Fully       5         2
426     LG   14990       7.5   780   Semi       5         2
429     LG    5290       7.5   300   Semi       5         2

('LG', 8.0)
    Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
42      LG   10799       8.0  1200   Semi       5         2
70      LG   40199       8.0  1000   Semi       5         2
154     LG   14390       8.0    10  Fully       5         2
177     LG    7274       8.0    16   Semi       5         2
189     LG   14890       8.0  1300   Semi       5         2
226     LG   20299       8.0  1200  Fully       5         2
249     LG   17690       8.0    10  Fully       5         2
264     LG   36990       8.0  1000  Fully       5         2
280     LG   42990       8.0  1400  Fully       5         3
284     LG   11699       8.0    10   Semi       5         2
290     LG   13990       8.0    12   Semi       5         2
321     LG   11900       8.0    10   Semi       5         2
325     LG   27390       8.0    12   Semi       5         2
389     LG   26899       8.0    12  Fully       5         2

('LG', 8.5)
    Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
6       LG   14990       8.5  1350   Semi       5         2
66      LG   14890       8.5  1000   Semi       5         3
208     LG   25900       8.5    10   Semi       5         2
209     LG    9699       8.5  1350  Fully       5         2
253     LG   22990       8.5   670  Fully       5         2
296     LG   15290       8.5    10   Semi       5         2

('LG', 9.0)
    Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
141     LG   17690       9.0   12   Semi       5         3
254     LG   21000       9.0   10  Fully       5         2

('Lifelong', 6.0)
       Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
133  Lifelong   31990       6.0  1300  Fully       5         2

('Lloyd', 4.6)
    Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
241  Lloyd   36990       4.6   12  Semi       5         4

('Lloyd', 6.0)
    Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
165  Lloyd    9990       6.0   10  Semi       5         2

('Lloyd', 7.0)
    Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
362  Lloyd   36990       7.0   10  Semi       5         3

('Lloyd', 7.5)
    Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
409  Lloyd   36990       7.5   22  Semi       5         2

('Lloyd', 8.0)
    Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
273  Lloyd   12990       8.0  800  Fully       5         2

('Lloyd', 8.5)
    Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
164  Lloyd   40990       8.5  680  Fully       5         4

('MOTOROLA', 6.5)
       Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
144  MOTOROLA   11900       6.5   10  Semi       5         2
388  MOTOROLA   11999       6.5  740  Semi       5         4

('MOTOROLA', 7.0)
       Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
76   MOTOROLA    8490       7.0    10   Semi       5         4
153  MOTOROLA    8244       7.0  1200  Fully       5         2

('MOTOROLA', 7.5)
       Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
160  MOTOROLA   15990       7.5  740  Semi       5         2

('MOTOROLA', 8.0)
       Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
116  MOTOROLA   20990       8.0  1200   Semi       5         2
156  MOTOROLA   40207       8.0  1400  Fully       5         4
341  MOTOROLA   24990       8.0   720   Semi       5         2

('MOTOROLA', 9.0)
       Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
126  MOTOROLA   36990       9.0  460  Fully       5         2

('MarQ', 6.0)
  Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
8   MarQ    6990       6.0   10  Semi       5         2

('MarQ', 6.5)
    Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
22    MarQ    7290       6.5  700   Semi       5         2
174   MarQ   39990       6.5   10  Fully       5         2
286   MarQ   74990       6.5   10  Fully       5         2

('MarQ', 7.0)
    Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
57    MarQ    8790       7.0  1350   Semi       5         3
80    MarQ   21790       7.0  1400  Fully       5         2
190   MarQ   26990       7.0   700   Semi       5         2
216   MarQ   14890       7.0    10   Semi       5         2
277   MarQ   23990       7.0  1350  Fully       5         4
294   MarQ   13799       7.0    10   Semi       5         2
397   MarQ   22990       7.0    15  Fully       5         2

('MarQ', 7.5)
    Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
74    MarQ   11240       7.5  1400  Fully       5         2
112   MarQ    9790       7.5   720  Fully       5         2
168   MarQ   14990       7.5  1400   Semi       5         2
289   MarQ   25500       7.5  1200  Fully       5         3

('MarQ', 8.0)
    Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
145   MarQ   11240       8.0   680   Semi       5         2
305   MarQ   24990       8.0    10  Fully       5         2
312   MarQ   14499       8.0  1400  Fully       5         2
402   MarQ    9699       8.0  1200   Semi       5         2

('MarQ', 8.5)
    Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
181   MarQ   31990       8.5   10  Fully       5         3

('Midea', 7.0)
   Brands  Prices  Capacity   RPM LOADS  Rating  Warranty
81  Midea   17290       7.0  1300  Semi       5         2

('Midea', 8.0)
    Brands  Prices  Capacity   RPM LOADS  Rating  Warranty
214  Midea   28999       8.0  1300  Semi       5         4

('Motorola', 6.0)
       Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
176  Motorola   34290       6.0   10  Semi       5         2

('Motorola', 7.0)
       Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
256  Motorola    9699       7.0   10  Fully       5         2

('Motorola', 7.5)
       Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
105  Motorola   19090       7.5   10  Fully       5         2


368  ONIDA   12655       9.0   16  Semi       5         3

('ONIDA', 9.5)
    Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
114  ONIDA   31990       9.5  1450  Fully       5         4

('Panasonic', 7.0)
        Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
328  Panasonic    8244       7.0   10  Semi       5         2
380  Panasonic   21500       7.0   10  Semi       5         3

('Panasonic', 7.2)
       Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
78  Panasonic    8244       7.2  800  Semi       3         2

('Panasonic', 7.5)
        Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
170  Panasonic   26590       7.5  740  Fully       5         2

('Panasonic', 8.0)
        Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
180  Panasonic   37330       8.0   12  Semi       5         2

('Panasonic', 8.5)
        Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
272  Panasonic   28990       8.5   10  Fully       5         2
309  Panasonic   16890       8.5   10   Semi       5         2

('RGL', 7.5)
    Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
436    RGL   16299       7.5   10  Semi       5         2

('SAMSUNG', 6.0)
      Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
34   SAMSUNG   23990       6.0   12  Fully       5         2
127  SAMSUNG   12900       6.0  780   Semi       5         2
314  SAMSUNG    7274       6.0   10  Fully       5         4
350  SAMSUNG   14890       6.0  740   Semi       5         3

('SAMSUNG', 6.5)
      Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
0    SAMSUNG   14490       6.5   680  Fully       3         2
29   SAMSUNG    9990       6.5    12  Fully       5         2
41   SAMSUNG   31990       6.5  1500  Fully       5         2
103  SAMSUNG   16490       6.5  1500   Semi       5         2
183  SAMSUNG   18990       6.5    10  Fully       5         2
196  SAMSUNG   21990       6.5  1000   Semi       5         2
219  SAMSUNG   17990       6.5   480   Semi       5         4
247  SAMSUNG   19499       6.5  1400  Fully       5         2
299  SAMSUNG   17690       6.5  1000   Semi       5         2
304  SAMSUNG   24490       6.5  1200   Semi       5         2
374  SAMSUNG   31990       6.5   740   Semi       5         2
415  SAMSUNG   23890       6.5  1300  Fully       5         3
416  SAMSUNG   31990       6.5  1400  Fully       5         2

('SAMSUNG', 6.7)
      Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
359  SAMSUNG   45990       6.7   12  Semi       5         3

('SAMSUNG', 7.0)
      Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
1    SAMSUNG   18490       7.0   750  Fully       5         3
10   SAMSUNG   10490       7.0  1400  Fully       5         2
24   SAMSUNG   27990       7.0  1400   Semi       5         3
69   SAMSUNG   29990       7.0  1450   Semi       5         2
71   SAMSUNG   22690       7.0    10  Fully       5         2
87   SAMSUNG   14190       7.0  1200   Semi       5         2
90   SAMSUNG    9990       7.0  1400   Semi       5         2
115  SAMSUNG   15990       7.0  1400  Fully       5         2
118  SAMSUNG    9990       7.0  1200   Semi       5         2
135  SAMSUNG    6640       7.0    10  Fully       5         2
146  SAMSUNG   12690       7.0  1400   Semi       5         2
163  SAMSUNG    8790       7.0    10  Fully       5         2
194  SAMSUNG   29990       7.0   700  Fully       5         2
223  SAMSUNG   18490       7.0    10   Semi       5         2
267  SAMSUNG    8244       7.0    10  Fully       5         3
270  SAMSUNG   19640       7.0    15  Fully       5         2
324  SAMSUNG   24990       7.0    15   Semi       3         2
367  SAMSUNG   19900       7.0    10  Fully       5         2
394  SAMSUNG   31990       7.0    10  Fully       5         2
423  SAMSUNG   13649       7.0  1400   Semi       5         2
439  SAMSUNG   31990       7.0    10   Semi       5         2

('SAMSUNG', 7.2)
      Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
151  SAMSUNG   16690       7.2  1000  Fully       5         3
171  SAMSUNG   28490       7.2    10   Semi       5         2
261  SAMSUNG   33490       7.2    10   Semi       5         3
370  SAMSUNG    7274       7.2    12  Fully       5         2

('SAMSUNG', 7.5)
      Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
203  SAMSUNG   36500       7.5    14  Fully       5         2
243  SAMSUNG    9499       7.5    16  Fully       5         2
291  SAMSUNG    8244       7.5   290   Semi       5         2
343  SAMSUNG   14800       7.5  1400   Semi       5         2
381  SAMSUNG    5499       7.5  1400  Fully       5         2

('SAMSUNG', 8.0)
      Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
3    SAMSUNG   36990       8.0  1450   Semi       5         3
7    SAMSUNG   31990       8.0   700  Fully       5         3
15   SAMSUNG   40199       8.0  1350   Semi       5         3
19   SAMSUNG   36899       8.0    10  Fully       5         3
27   SAMSUNG   36990       8.0   800   Semi       5         2
31   SAMSUNG   31990       8.0    11  Fully       5         2
47   SAMSUNG   18190       8.0  1400   Semi       5         2
51   SAMSUNG   15390       8.0    12  Fully       5         2
62   SAMSUNG    9699       8.0  1200   Semi       5         2
85   SAMSUNG   35990       8.0   720   Semi       5         2
238  SAMSUNG   39990       8.0    10  Fully       5         3
257  SAMSUNG   33290       8.0   800  Fully       5         2
275  SAMSUNG   17690       8.0    10  Fully       5         3
278  SAMSUNG   42360       8.0  1400  Fully       5         4
285  SAMSUNG   11390       8.0  1400  Fully       5         2
287  SAMSUNG   36990       8.0   740   Semi       5         2
293  SAMSUNG   19990       8.0  2000   Semi       5         2
300  SAMSUNG   36899       8.0    10  Fully       5         2
323  SAMSUNG   21500       8.0  1000   Semi       5         2
326  SAMSUNG   14890       8.0  1300  Fully       5         3
339  SAMSUNG   15990       8.0    10  Fully       5         2
348  SAMSUNG   10399       8.0    10   Semi       5         2
349  SAMSUNG   26499       8.0  1300   Semi       5         3
366  SAMSUNG    8990       8.0  2000   Semi       5         2
385  SAMSUNG   23015       8.0   665   Semi       5         2
399  SAMSUNG   36500       8.0  1200   Semi       5         3
404  SAMSUNG   14890       8.0  1400   Semi       5         2
421  SAMSUNG   26200       8.0  1400   Semi       5         3

('SAMSUNG', 8.5)
      Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
32   SAMSUNG   13490       8.5    10   Semi       5         2
97   SAMSUNG   21490       8.5   740   Semi       5         2
195  SAMSUNG   22490       8.5    10  Fully       5         2
306  SAMSUNG   14890       8.5  1400  Fully       5         2
315  SAMSUNG   37739       8.5   740  Fully       5         2
338  SAMSUNG   31990       8.5  1000   Semi       5         2
379  SAMSUNG   16630       8.5  1200   Semi       5         3
424  SAMSUNG   14890       8.5    10   Semi       5         3

('SAMSUNG', 9.0)
      Brands  Prices  Capacity   RPM LOADS  Rating  Warranty
239  SAMSUNG   11090       9.0    10  Semi       5         2
269  SAMSUNG   13590       9.0  1400  Semi       5         2
318  SAMSUNG   31990       9.0    10  Semi       5         3
387  SAMSUNG   15490       9.0  1350  Semi       5         2

('Samsung', 8.0)
      Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
378  Samsung    9990       8.0   10  Fully       5         4

('Sansui', 7.0)
    Brands  Prices  Capacity   RPM LOADS  Rating  Warranty
77  Sansui   16790       7.0  1500  Semi       5         2

('Sansui', 8.0)
     Brands  Prices  Capacity   RPM LOADS  Rating  Warranty
130  Sansui    8990       8.0  1400  Semi       5         2
204  Sansui   11990       8.0    10  Semi       5         2

('Sansui', 9.0)
     Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
313  Sansui   17199       9.0   14  Fully       5         3

('Singer', 7.0)
     Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
125  Singer   15390       7.0   10  Semi       5         3

('TCL', 6.0)
    Brands  Prices  Capacity   RPM LOADS  Rating  Warranty
337    TCL   49959       6.0  1500  Semi       5         2
417    TCL   48990       6.0    10  Semi       5         3

('TCL', 9.0)
    Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
162    TCL   10090       9.0  700  Fully       5         2

('TOSHIBA', 7.2)
      Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
334  TOSHIBA   36990       7.2   15  Semi       5         3

('Thomson', 6.0)
      Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
132  Thomson    6990       6.0   15  Fully       5         2

('Thomson', 6.5)
     Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
20  Thomson    6990       6.5  740  Semi       5         2

('Thomson', 7.5)
     Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
96  Thomson   19490       7.5   10  Fully       5         2
98  Thomson   11240       7.5   12  Fully       5         2

('Thomson', 8.0)
     Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
93  Thomson   35990       8.0   12  Fully       5         2

('Thomson', 9.0)
      Brands  Prices  Capacity   RPM LOADS  Rating  Warranty
102  Thomson   36990       9.0  1300  Semi       5         2

('Voltas', 6.5)
     Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
410  Voltas   13900       6.5   10  Semi       5         2

('Voltas', 7.5)
     Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
268  Voltas   13690       7.5  1400  Fully       5         2
353  Voltas    5499       7.5   800   Semi       5         2

('Whirlpool', 3.0)
        Brands  Prices  Capacity   RPM LOADS  Rating  Warranty
365  Whirlpool   28290       3.0  1450  Semi       5         2

('Whirlpool', 6.0)
        Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
17   Whirlpool   13990       6.0    12   Semi       5         2
25   Whirlpool    8990       6.0    22  Fully       5         2
82   Whirlpool    8990       6.0  1400  Fully       5         3
83   Whirlpool   20990       6.0    22   Semi       5         2
104  Whirlpool   28990       6.0  1000   Semi       5         2
207  Whirlpool   13990       6.0   800   Semi       5         2
283  Whirlpool   40199       6.0   700   Semi       5         2
298  Whirlpool   29390       6.0    10   Semi       5         2
383  Whirlpool   24990       6.0   740  Fully       5         2
435  Whirlpool    8990       6.0  1400  Fully       5         2

('Whirlpool', 6.5)
        Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
52   Whirlpool   11240       6.5  1350   Semi       5         2
95   Whirlpool   11990       6.5   700   Semi       5         2
106  Whirlpool    8990       6.5  1400  Fully       5         3
107  Whirlpool   17990       6.5  1400   Semi       5         2
172  Whirlpool    5190       6.5    12  Fully       5         4
288  Whirlpool   43699       6.5    12   Semi       5         3
303  Whirlpool   30990       6.5   750  Fully       5         4
327  Whirlpool   19990       6.5  1000  Fully       5         3
355  Whirlpool   25590       6.5    12  Fully       5         2
384  Whirlpool   17290       6.5    10  Fully       5         2
412  Whirlpool   36590       6.5    10  Fully       5         2

('Whirlpool', 7.0)
        Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
2    Whirlpool    9990       7.0    12   Semi       5         2
13   Whirlpool   16590       7.0   700  Fully       5         2
67   Whirlpool    7990       7.0    15   Semi       5         4
75   Whirlpool   20990       7.0    10   Semi       5         2
136  Whirlpool   32290       7.0  1500   Semi       5         2
184  Whirlpool   41290       7.0   700  Fully       5         4
265  Whirlpool    5750       7.0    10   Semi       5         2
274  Whirlpool   29990       7.0  1400   Semi       5         2
360  Whirlpool   11337       7.0    10   Semi       5         4
363  Whirlpool   10490       7.0  1000   Semi       5         2
372  Whirlpool    8290       7.0  1400  Fully       5         2
427  Whirlpool   19290       7.0    10  Fully       5         2

('Whirlpool', 7.5)
        Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
11   Whirlpool   17690       7.5    10  Fully       5         2
33   Whirlpool   17690       7.5  1400  Fully       5         3
53   Whirlpool   11990       7.5   700  Fully       5         4
55   Whirlpool   18590       7.5  1400   Semi       5         2
92   Whirlpool    8199       7.5   740   Semi       5         2
99   Whirlpool   14150       7.5   720   Semi       5         2
119  Whirlpool   22990       7.5    10   Semi       5         2
139  Whirlpool   34990       7.5    15   Semi       5         4
143  Whirlpool   10690       7.5   800   Semi       5         2
212  Whirlpool   20390       7.5  1400   Semi       5         4
215  Whirlpool   25490       7.5   800   Semi       5         2
218  Whirlpool   18490       7.5  1400  Fully       5         2
220  Whirlpool   35890       7.5   780   Semi       5         2
258  Whirlpool   13600       7.5   700  Fully       5         1
263  Whirlpool   29990       7.5   700   Semi       3         3
311  Whirlpool   16290       7.5    10   Semi       5         3
403  Whirlpool   30470       7.5  1440  Fully       5         2

('Whirlpool', 8.0)
        Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
91   Whirlpool   14940       8.0    10   Semi       5         2
101  Whirlpool   25490       8.0  1350   Semi       5         2
123  Whirlpool   24670       8.0    10  Fully       5         2
131  Whirlpool    4990       8.0  1400   Semi       5         2
147  Whirlpool   34590       8.0    12  Fully       5         2
159  Whirlpool   42490       8.0    10   Semi       5         3
167  Whirlpool   27990       8.0    16   Semi       5         2
191  Whirlpool   16799       8.0    10  Fully       5         2
210  Whirlpool   19990       8.0   700  Fully       5         2
224  Whirlpool   13890       8.0  1400   Semi       5         2
227  Whirlpool    9990       8.0    12   Semi       5         2
251  Whirlpool   22290       8.0    14   Semi       5         2
276  Whirlpool   17490       8.0  1300  Fully       5         2
279  Whirlpool   14890       8.0  1450  Fully       5         2
344  Whirlpool   34299       8.0    10  Fully       5         3
347  Whirlpool    7990       8.0    14   Semi       5         2
431  Whirlpool   17700       8.0    12  Fully       5         2

('Whirlpool', 8.5)
        Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
39   Whirlpool   14890       8.5    10   Semi       5         4
157  Whirlpool    8990       8.5  1400   Semi       5         2
331  Whirlpool   15490       8.5  1200   Semi       5         2
371  Whirlpool   28690       8.5  1450  Fully       5         2

('Whirlpool', 9.0)
        Brands  Prices  Capacity   RPM LOADS  Rating  Warranty
187  Whirlpool   31990       9.0  1500  Semi       5         2

('Whirlpool', 9.5)
        Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
438  Whirlpool   13990       9.5  700  Semi       5         2

('White', 6.5)
    Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
248  White    6099       6.5  700  Semi       5         2

('White', 7.0)
    Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
117  White   15700       7.0   10  Semi       5         3
361  White   55900       7.0  700  Semi       5         2

('White', 7.2)
    Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
317  White   16230       7.2  1200  Fully       5         2

('White', 8.0)
    Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
137  White    9990       8.0   700  Fully       5         2
217  White   36990       8.0  1350  Fully       5         2
245  White   31990       8.0  1400  Fully       5         4

('realme', 6.0)
     Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
120  realme   34990       6.0   10  Fully       5         2

('realme', 6.5)
    Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
54  realme   17690       6.5   10  Fully       5         2

('realme', 7.0)
    Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
68  realme   30490       7.0   12  Fully       5         2

('realme', 7.5)
    Brands  Prices  Capacity  RPM LOADS  Rating  Warranty
64  realme   13990       7.5   10  Semi       5         3

('realme', 8.0)
   Brands  Prices  Capacity   RPM  LOADS  Rating  Warranty
9  realme   14990       8.0  1300  Fully       5         2

('realme', 8.5)
    Brands  Prices  Capacity  RPM  LOADS  Rating  Warranty
45  realme    6990       8.5  270  Fully       5         3

In [27]:
df1[['Brands','Prices','Capacity','RPM']].min()

Brands      BOSCH
Prices       4990
Capacity      3.0
RPM            10
dtype: object

In [28]:
df1[['Brands','Prices','Capacity','RPM']].max()

Brands      realme
Prices      109090
Capacity       9.5
RPM           2000
dtype: object

In [29]:
df2=df1.to_csv("DATA CLEANED .csv")


## Advantages of semi automatic washing machine

#### Does not continous water supply. This will much helpful if you are living in water crisis area.
#### Small duration wash cycle.
#### Consumes less water compared to fully automatic washing machine.
#### Lightweight, easily movable